{"name": "删除渠道", "status": "broken", "statusDetails": {"message": "Exception: error happend", "trace": "self = <testcases.test_02.Test2 object at 0x11021bf98>\n\n    @allure.title('删除渠道')\n    @allure.description_html('创建渠道')\n    def test_4(self):\n        with allure.step('输出'):\n>           raise Exception('error happend')\nE           Exception: error happend\n\ntest_02.py:23: Exception"}, "descriptionHtml": "创建渠道", "steps": [{"name": "输出", "status": "broken", "statusDetails": {"message": "Exception: error happend\n", "trace": "  File \"/Users/ppll/Desktop/test/testcases/test_02.py\", line 23, in test_4\n    raise Exception('error happend')\n"}, "start": 1563036280892, "stop": 1563036280892}], "start": 1563036280892, "stop": 1563036280892, "uuid": "a87cbdb0-9c37-4915-a8fb-3034eca0366b", "historyId": "14220c630e201a74973ff5ac6fcc3e95", "fullName": "test_02.Test2#test_4", "labels": [{"name": "story", "value": "渠道管理"}, {"name": "feature", "value": "基础平台"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_02"}, {"name": "subSuite", "value": "Test2"}, {"name": "host", "value": "pplldemac-mini"}, {"name": "thread", "value": "10210-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02"}]}